### ISSUE TITLE
Documentar

### ISSUE THREAD

**Issue by 2314-RAustin** [theLastPixel/WW-Shutter#107]
Semana 3

**Comment by 2314-RAustin** [comment]
Queda pendiente esta documentación hasta terminar los 5 modificación a realizar
![imagen](https://user-images.githubusercontent.com/36521586/56327071-87b94780-612d-11e9-899b-95c64c30513f.png)

**Comment by 2314-RAustin** [comment]
Aun ahí pendientes

- [ ] - 1. Cambiar el logotipo #82 
- [ ] - 2. Traducción funcional #86 
- [x] - 3. Agregar imagen shutter arco #102 
- [ ] - 4. Agregar tips al menú #94 
- [x] - 5. Crear la interfaz de tip 1 #96 y #97 
- [x] - 6. Crear la interfaz de tip 2 #96 y #97 
- [ ] - 7. Agregar nuestro equipo de trabajo al menú derivado de nosotros #90
- [x] - 8. Crear la interfaz de nuestro trabajo. #98 y #99
